name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Clear Cypress cache
      - name: Clear Cypress cache
        run: npx cypress cache clear

      # Install npm dependencies
      - name: Install dependencies
        run: npm install

      # Run the login script
      - name: Run login test
        run: npm run login
